package com.star.frame.component.datastore.dao;

import com.star.frame.component.model.CptDataStore;
import com.star.frame.component.model.CptDataStoreExample;
import com.star.frame.core.base.CoreDao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CptDataStoreMapper extends CoreDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int countByExample(CptDataStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int deleteByExample(CptDataStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int insert(CptDataStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int insertSelective(CptDataStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    List<CptDataStore> selectByExample(CptDataStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    CptDataStore selectByPrimaryKey(String id);
    
    CptDataStore selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int updateByExampleSelective(@Param("record") CptDataStore record, @Param("example") CptDataStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int updateByExample(@Param("record") CptDataStore record, @Param("example") CptDataStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int updateByPrimaryKeySelective(CptDataStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HFMIS_V8.CPT_DATASTORE
     *
     * @mbggenerated Wed Jun 05 09:51:42 CST 2013
     */
    int updateByPrimaryKey(CptDataStore record);
}