package com.star.frame.component.model;

public class CptExportCfg extends CptExportCfgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.EXPORT_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    private String exportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.SERVICE_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.COLUMN_INFO
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    private String columnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.QUERY_SQL
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    private String querySql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.NAME
     *
     * @return the value of HFMIS_GUIYANG.CPT_EXPORT_CFG.NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.NAME
     *
     * @param name the value for HFMIS_GUIYANG.CPT_EXPORT_CFG.NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.EXPORT_NAME
     *
     * @return the value of HFMIS_GUIYANG.CPT_EXPORT_CFG.EXPORT_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public String getExportName() {
        return exportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.EXPORT_NAME
     *
     * @param exportName the value for HFMIS_GUIYANG.CPT_EXPORT_CFG.EXPORT_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public void setExportName(String exportName) {
        this.exportName = exportName == null ? null : exportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.SERVICE_NAME
     *
     * @return the value of HFMIS_GUIYANG.CPT_EXPORT_CFG.SERVICE_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.SERVICE_NAME
     *
     * @param serviceName the value for HFMIS_GUIYANG.CPT_EXPORT_CFG.SERVICE_NAME
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.COLUMN_INFO
     *
     * @return the value of HFMIS_GUIYANG.CPT_EXPORT_CFG.COLUMN_INFO
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public String getColumnInfo() {
        return columnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.COLUMN_INFO
     *
     * @param columnInfo the value for HFMIS_GUIYANG.CPT_EXPORT_CFG.COLUMN_INFO
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public void setColumnInfo(String columnInfo) {
        this.columnInfo = columnInfo == null ? null : columnInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.QUERY_SQL
     *
     * @return the value of HFMIS_GUIYANG.CPT_EXPORT_CFG.QUERY_SQL
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public String getQuerySql() {
        return querySql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HFMIS_GUIYANG.CPT_EXPORT_CFG.QUERY_SQL
     *
     * @param querySql the value for HFMIS_GUIYANG.CPT_EXPORT_CFG.QUERY_SQL
     *
     * @mbggenerated Fri Sep 14 16:05:34 CST 2012
     */
    public void setQuerySql(String querySql) {
        this.querySql = querySql == null ? null : querySql.trim();
    }
}